# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Futu"
license = "MIT"
licenselink = "https://github.com/masakichi/futu/blob/master/LICENSE"
description = "Yet another minimal hugo theme, built-in styles are modified upon awsm.css."
homepage = "https://github.com/masakichi/futu"
tags = ["blog", "minimal"]
features = []
min_version = "0.89.0"

[author]
  name = "Yuanji"
  homepage = "https://blog.gimo.me"
